################################################################################
# Copyright 2016 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.8.7
# Author: "spriteCloud B.V." <info@spritecloud.com>

# interactions_steps.rb is used to interact with elements on the page.

Given(/^the user navigates to (.*?) in (.*?)$/) do |site, language|
  # Combine the configuration depth with dots
  config_name = "#{site.downcase}.#{language.downcase}"
  # Get the value of the configuration (see /config/config.yml)
  url         = env(config_name)
  # Go to the URL
  browser.goto url
end

Given(/^the user searches for "(.*?)"$/) do |query|
  # Get the input element
  searchbox = browser.find(:text_field => {:name => "q"})
  # Make sure the input field is empty
  searchbox.clear rescue log.debug "Could not clear searchbox"
  # Fill in the query
  searchbox.send_keys(query)
  # Press enter to submit the search
  searchbox.send_keys(:enter)
end

When(/^the user clicks on link "(.*?)"$/) do |url|
  # Search for the element that includes the expected text
  browser.wait(
    :like => {
      :element   => :a,
      :attribute => :href,
      :include   => url
    }
  ).click
end

$TIME_SLEPT = 0
Given(/^I sleep for "([^"]*)" seconds$/) do |arg1|
  log.debug "Going to sleep for #{arg1} seconds"
  sleep arg1.to_i
  $TIME_SLEPT += arg1.to_i
end

Then(/^I should log my total sleeping time$/) do 
  log.debug "Slept a total time of #{$TIME_SLEPT} seconds"
end

Given(/^I sleep "([^"]*)" times for "([^"]*)" seconds$/) do |arg1, arg2|
  loops = arg1.to_i
  log.debug "Going to sleep #{arg2} seconds for #{arg1} times"
  i = 1
  while loops < i
    sleep arg2.to_i
    $TIME_SLEPT += arg2.to_i
  end
end