################################################################################
# Copyright 2016 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.8.7
# Author: "spriteCloud B.V." <info@spritecloud.com>

# validation_steps.rb is used to confirm that certain elements are displayed on the page.

Then(/text "([^"]*)" should display/) do |string|
  # Note: The following is *really* slow, as it'll apply the regex to all
  #       elements in the page, one after the other. Of course, if any element
  #       includes the regex, all its parent elements also will, so you have
  #       tons of matches to process.
  #
  # browser.wait(:text => /#{string}/i)

  #       Instead, you will want to search only the root element for some
  #       text, e.g.
  #
  # browser.wait(:html => {:text => /#{string}/i})

  #       There's a shortcut for that in find/wait:
  browser.wait(:html => /#{string}/i)
end